spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.100.71:3306/log4j_demo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:webuser}
    password: ${SPRING_DATASOURCE_PASSWORD:webuser}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 연결 풀 설정
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul

  thymeleaf:
    cache: true

# 로깅 설정
logging:
  config: classpath:log4j2.xml
  level:
    com.example.demo: INFO
    root: WARN

# 서버 설정
server:
  port: 8080
  error:
    whitelabel:
      enabled: false